[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_API_URL = "https://fit-journey-chronicle-api-8e2962c34ae8.herokuapp.com/api" 