[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://fit-journey-chronicle-api-8e2962c34ae8.herokuapp.com/api/:splat"
  status = 200
  force = true

[build.environment]
  VITE_API_URL = "https://fit-journey-chronicle-api-8e2962c34ae8.herokuapp.com/api" 